
shared:
    image: golang:latest
    environment:
        GOPATH: /sd/workspace
        
jobs:
    detached:
        steps:
            - meta get foo bar
    detached_second:
        requires: detached
        steps:
            - meta get foo
    source_main:
        sourcePaths: ["README.md"]
        requires: [~commit, ~pr]
        settings:
            slack: 
              - test-slack-notif
              - test-slack-min
        steps:
            - ram: free -h && cat /proc/cpuinfo
            - cat: cat access_log && sleep 100
            
    job2:
        requires: main
        steps:
            - mem_cpu: nproc --all && free -h 
            - hab: ls /hab/pkgs/core
            - meta: meta set foo bar
            - write: echo 'aa' > /sd/meta/test.json
    main:
        annotations:
            screwdriver.cd/cpu: TURBO
            beta.screwdriver.cd/ram: TURBO
       image: python
       requires: [~pr,~commit]
       steps:
           - mem_cpu: nproc --all && free -h 
           - echo-1: echo hi
           - echo-2: echo $SD_PIPELINE_NAME
           - cat: free -m 
