
shared:
    description: 'hi!@@'
    image: golang:latest
    steps:
      - test1: &test1 echo shared
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        requires: [~commit, ~pr]
        steps:
            - print: echo Starting main
    other_main:
        requires: ~commit
        steps:
            - print: echo Starting another mai
