
shared:
    image: golang:latest
    environment:
        GOPATH: /sd/workspace
        
jobs:
    test_test_main:
        requires: [~commit, ~pr, ~sd@241:main]
        steps:
            - sleep: sleep 500
            - print: echo $SD_PULL_REQUEST
    publish:
       requires: no_main
       steps:
           - print: echo running publish
    other_publish:
       requires: wow_new_main
       steps:
           - print: echo running other_publish
    wow_new_main:
       requires: [~commit, ~pr, ~sd@241:main]
       steps:
           - other_print: echo running other_main
