
workflow:
    - publish
shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        environment:
            EMAIL: min@gmail.com
        image: golang
        steps:
            - clone: git clone https://github.com/tk3fftk/meta-cli.git
            - checkout: cd meta-cli && git checkout meta-cli
            - build: go build -a -o meta-cli
            - run: sudo chmod 600 /sd/meta
            - set: ./meta-cli set foo bar &&  echo $?
            - get: ./meta-cli get foo
            - print: echo the main jobs started!
            - check-go-img: go version
    publish:
        steps:
            - install: npm install
            - echo: echo $SD_TOKEN
            - setup-ci: git clone https://gist.github.com/3d2388b2a7ba658cdcdaffa8cd874e50.git ci
            - release: ./ci/git-release.sh
        secrets:
            - GITHUB_TOKEN
        environment:
            RELEASE_FILE: README.md
