
shared:
    image: golang:latest
    environment:
        GOPATH: /sd/workspace
        
jobs:
    detached:
        steps:
            - meta get foo bar
    detached_second:
        requires: detached
        steps:
            - meta get foo
    no_main:
        requires: [~commit, ~pr, ~sd@241:main]
        steps:
            - cat: cat logs.txt
            - print: echo $SD_PULL_REQUEST
            - sleep: sleep 1
            - echo: echo hello
            - test: echo world
        settings:
            slack: 
              - test-slack-notif
              - test-slack-min
    new_job:
        requires: [~pr, ~commit]
        steps:
           - print: echo running new_job
    publish:
       requires: no_main
       steps:
           - print: echo running publish
