
shared:
    image: golang:latest
    environment:
        GOPATH: /sd/workspace
        
jobs:
    detached:
        steps:
            - meta get foo bar
    detached_second:
        requires: detached
        steps:
            - meta get foo
    no_main:
        requires: [~commit, ~pr]
        settings:
            slack: 
              - test-slack-notif
              - test-slack-min
        steps:
            - cat: cat logs.txt
    wow_new_main:
       image: python
       requires: [~pr,~commit]
       steps:
           - echo: echo $SD_PIPELINE_NAME
           - test: python test.py && ps aux 
