
shared:
    image: golang:latest
    environment:
        GOPATH: /sd/workspace
        
jobs:
    no_main:
        requires: [~commit, ~pr, ~sd@241:main]
        steps:
            - print: echo $SD_PULL_REQUEST
            - sleep: sleep 1
            - echo: echo hello
            - test: echo world
        settings:
            slack: 
                channels: 
                   - test-slack-notif
                statuses:
                   - SUCCESS
                   - FAILURE
                   - ABORTED
                   - QUEUED
                   - RUNNING
    publish:
       requires: no_main
       steps:
           - print: echo running publish
    other_publish:
       requires: wow_new_main
       steps:
           - print: echo running other_publish
    wow_new_main:
       requires: [~commit, ~pr, ~sd@241:main]
       steps:
           - other_print: echo running other_main
