annotations:
    beta.test: 123

shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
    annotations:
        screwdriver.cd/buildPeriodically: H 45 * * *
        
jobs:
    detached:
        requires: [~pr, ~commit]
        steps:
            - echo: echo detached
    main:
        requires: [~pr, ~commit]
        steps:
            - who: whoami
            - set: meta set foo bar
            - get: meta get foo
            - newstep: echo new!
    second_main:
        requires: [main]
        steps:
            - get: meta get foo && meta get foo --external sd@175:main
    third:
        requires: [main]
        steps:
            - get: meta get foo && meta get foo --external sd@175:main
            # - exit: exit 1
    last:
        requires: [second_main,third]
        steps:
            - get: meta get foo && meta get foo --external sd@175:main

