
workflow:
    - publish
shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            - test: echo $PREFIX && echo $PREFIX2
            - py: python ./config.py
            - meta: meta set foo bar
            - meta-get: meta get foo
            - echo: echo hello
            - check-go-img: go version
        environment: 
            PREFIX: beta-
            PREFIX2: 'beta-'
    publish:
        steps:
            - echo: echo $SD_TOKEN
