
shared:
    image: golang:latest
    environment:
        GOPATH: /sd/workspace
        
jobs:
    no_main:
        requires: [~commit, ~pr, ~sd@241:main]
        steps:
            - print: echo running main
    other_main:
        requires: [~commit, ~pr]
        steps:
            - other_print: echo running other_main
    publish:
       requires: no_main
       steps:
           - print: echo running publish
    other_publish:
       requires: other_main
       steps:
           - print: echo running other_publish
