workflow:
    - publish
shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            - set: meta set foo bar
            - ls: ls
    publish:
        steps:
            - meta-get: meta get foo
            - echo: meta set foo new
            - echo: meta get foo
