
workflow:
    - publish
shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            - test: sd-step exec core/tomcat8 echo done
            - meta: meta set foo bar
            - meta-get: meta get foo
            - echo: echo hello
            - exit: exit 1
            - print: echo the main jobs started!
            - check-go-img: go version
    publish:
        steps:
            - echo: echo $SD_TOKEN
