
shared:
    image: golang:latest
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        requires: [~commit, ~pr]
        steps:
            - print: echo running main
    o_main:
        requires: [~commit, ~pr]
        steps:
            - other_print: echo running other_main
    publish:
       requires: main
       steps:
           - print: echo running publish
    other_publish:
       requires: other_main
       steps:
           - other_print: echo running other_publis
