
shared:
    image: golang:latest
    environment:
        GOPATH: /sd/workspace
        
jobs:
    detached:
        steps:
            - meta get foo bar
    detached_second:
        requires: detached
        steps:
            - meta get foo
    no_main:
        template: minz/nodejs_main
        requires: [~commit, ~pr, ~sd@241:main]
        steps:
            - preinstall: echo $SD_TEMPLATE_NAME && echo $SD_TEMPLATE_VERSION && env && sleep 10000
        settings:
            slack: 
              - test-slack-notif
              - test-slack-min
    publish:
       requires: no_main
       steps:
           - print: echo running publish
    other_publish:
       requires: xxxx_test
       steps:
           - print: echo running other_publish
    xxxx_test:
       requires: [~pr,~commit, ~sd@241:main]
       steps:
           - other_print: echo $SD_TEMPLATE_NAME && echo $SD_TEMPLATE_VERSION
           - rm: rm -rf `which curl`
           - set: meta set docker_tag `git describe --tags`
           - get: meta get docker_tag
