
workflow:
    - publish
shared:
    image: node:6
jobs:
    main:
        environment:
            EMAIL: min@gmail.com
        image: golang
        steps:
            - whoami: whoami
            - print: echo the main jobs started!
            - check-go-img: go version
    publish:
        steps:
            - install: npm install
            - echo: echo $SD_TOKEN
            - setup-ci: git clone https://gist.github.com/3d2388b2a7ba658cdcdaffa8cd874e50.git ci
            - release: ./ci/git-release.sh
        secrets:
            - GITHUB_TOKEN
        environment:
            RELEASE_FILE: README.md
