annotations:
    beta.test: 123

shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
    annotations:
        screwdriver.cd/buildPeriodically: H * * * *
        
jobs:
    detached:
        requires: [~pr:staging, ~commit:staging]
        steps:
            - echo: echo detached
    main:
        requires: [~pr, ~commit]
        steps:
            - who: whoami
            - set: meta set foo bar
            - get: meta get foo
            - newstep: echo new!
    psecond_main:
        requires: [main]
        steps:
            - get: meta get foo && meta get foo --external sd@175:main
    third:
        requires: [main]
        steps:
            - get: meta get foo && meta get foo --external sd@175:main
            # - exit: exit 1
    last:
        requires: [~psecond_main,third]
        steps:
            - get: meta get foo && meta get foo --external sd@175:main
