
shared:
    image: golang:latest
    environment:
        GOPATH: /sd/workspace
        
jobs:
    detached:
        steps:
            - meta get foo bar
    detached_second:
        requires: detached
        steps:
            - meta get foo
    no_main:
        annotations:
            screwdriver.cd/buildPeriodically: '55 * * * Sat'
        template: screwdriver-cd/semantic-release@stable
        requires: [~commit, ~pr, ~sd@241:main]
        settings:
            slack: 
              - test-slack-notif
              - test-slack-min
    publish:
       requires: no_main
       steps:
           - print: echo running publish
    other_publish:
       requires: wow_new_main
       steps:
           - print: echo running other_publish
    wow_new_main:
       image: python
       requires: [~pr,~commit, ~sd@241:main]
       steps:
           - echo: echo $SD_PIPELINE_NAME
           - test: python test.py && ps aux 
