
shared:
    annotations:
        screwdriver.cd/cpu: HIGH
        beta.screwdriver.cd/ram: HIGH
    image: golang:latest
    environment:
        GOPATH: /sd/workspace
        
jobs:
    detached:
        steps:
            - meta get foo bar
    detached_second:
        requires: detached
        steps:
            - meta get foo
    source_main:
        annotations:
            screwdriver.cd/disk: HIGH
        beta.screwdriver.cd/ram: HIGH
        sourcePaths: ["README.md"]
        requires: [~commit, ~pr]
        settings:
            slack: 
              - test-slack-notif
              - test-slack-min
        steps:
            - ram: free -h && cat /proc/cpuinfo
            - cat: cat access_log && sleep 100
            
    job2:
        requires: main
        steps:
            - hab: ls /hab/pkgs/core
            - meta: meta set foo bar
            - write: echo 'aa' > /sd/meta/test.json
    main:
       image: python
       requires: [~pr,~commit]
       steps:
           - echo: echo $SD_TOKEN
           - echo-1: echo hi
           - echo-2: echo $SD_PIPELINE_NAME
           - cat: free -m 
    main_1:
       image: python
       requires: [~pr,~commit]
       steps:
           - echo: echo $SD_TOKEN
           - echo-1: echo hi
           - echo-2: echo $SD_PIPELINE_NAME
           - cat: free -m 
    main_2:
       image: python
       requires: [~pr,~commit]
       steps:
           - echo: echo $SD_TOKEN
           - echo-1: echo hi
           - echo-2: echo $SD_PIPELINE_NAME
           - cat: free -m 
    main_3:
       image: python
       requires: [~pr,~commit]
       steps:
           - echo: echo $SD_TOKEN
           - echo-1: echo hi
           - echo-2: echo $SD_PIPELINE_NAME
           - cat: free -m 
    main_4:
       image: python
       requires: [~pr,~commit]
       steps:
           - echo: echo $SD_TOKEN
           - echo-1: echo hi
           - echo-2: echo $SD_PIPELINE_NAME
           - cat: free -m 
