
shared:
    description: 'hi!@@'
    image: golang:latest
    steps:
      - test1: &test1 echo shared
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            - sleep: sleep 10
            - print: echo Starting main job
    second:
        steps:
            - print: echo Starting second jo
